package:
  name: olivar
  version: 0.9.0

source:
  git_url: https://gitlab.com/treangenlab/olivar.git

build:
  number: 0
  noarch: generic

requirements:
  host:
    - python 3.7
  run:
    - python 3.7
    - biopython
    - tqdm
    - numpy
    - pandas
    - jinja2
    - parsnp=1.5
    - primer3
    - blast
    - mafft
    - pyvcf
    - pysam
    - samtools
    - minimap2
    - bowtie2
    - lofreq

test:
  commands:
    - olivar
  
about:
  home: https://gitlab.com/treangenlab/olivar
  license: TreangenLab
  summary: An open source pipeline for comprehensive design of primer and probe sets for pathogen sequences
